### ISSUE TITLE
Error on shutdown (Waterfall 1.17)

### ISSUE THREAD

**Issue by Tobi-Jakka** [xxneox/EpicGuard#122]
Error msg:
https://paste.gg/p/anonymous/0145bf77af6d4841a7ee62e8134b2da4

**Comment by Tobi-Jakka** [comment]
Also it gave me this when the proxy was starting up: https://paste.gg/p/anonymous/4e668929db004c139c1841ae808bfee7

**Comment by xxneox** [comment]
Try latest build, it should show you more detailed error: https://github.com/xxneox/EpicGuard/suites/3871122794/artifacts/96305870

**Comment by Tobi-Jakka** [comment]
`[12:21:16 INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.17-R0.1-SNAPSHOT:306121c:449 by WaterfallMC
[12:21:16 INFO] [EpicGuard]: Running on: Waterfall-git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449
[12:21:16 INFO] [EpicGuard]: Loading configuration...
[12:21:16 INFO] [EpicGuard]: Initializing managers...
[12:21:16 INFO] [EpicGuard]: This product includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com
[12:21:16 INFO] [DB]: Connecting to Database: mysql://172.17.0.1:3306/s8_epicguard
[12:21:16 INFO] [me.xneox.epicguard.libs.hikari.HikariDataSource]: DB - Starting...
[12:21:16 INFO] [me.xneox.epicguard.libs.hikari.pool.HikariPool]: DB - Added connection com.mysql.jdbc.JDBC4Connection@78e17a99
[12:21:16 INFO] [me.xneox.epicguard.libs.hikari.HikariDataSource]: DB - Start completed.
[12:21:16 ERROR] [EpicGuard]: An error occurred in EpicGuard!
[12:21:16 ERROR] [EpicGuard]:   > Details: Could not load data from SQL database
[12:21:16 ERROR] [EpicGuard]:   > Platform: Waterfall-git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449
[12:21:16 ERROR] [EpicGuard]:   > Stacktrace: 
[12:21:16 ERROR] [EpicGuard]: 
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.Number (java.lang.Boolean and java.lang.Number are in module java.base of loader 'bootstrap')
        at me.xneox.epicguard.libs.idb.DbRow.getInt(DbRow.java:73) ~[?:?]
        at me.xneox.epicguard.core.storage.SQLDatabase.loadData(SQLDatabase.java:73) ~[?:?]
        at me.xneox.epicguard.core.storage.StorageManager.<init>(StorageManager.java:46) ~[?:?]
        at me.xneox.epicguard.core.EpicGuard.startup(EpicGuard.java:70) ~[?:?]
        at me.xneox.epicguard.core.EpicGuard.<init>(EpicGuard.java:58) ~[?:?]
        at me.xneox.epicguard.waterfall.EpicGuardWaterfall.onEnable(EpicGuardWaterfall.java:48) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
[12:21:16 INFO] [EpicGuard]: Initializing LogFilter...
[12:21:16 INFO] [EpicGuard]: Scheduling tasks...
[12:21:16 INFO] [EpicGuard]: Startup completed successfully. Welcome to EpicGuard v7.1.0
[12:21:16 INFO] [EpicGuard]: Order of the detection pipeline: LockdownCheck, BlacklistCheck, NicknameCheck, GeographicalCheck, ServerListCheck, ReconnectCheck, AccountLimitCheck, NameSimilarityCheck, ProxyCheck
[12:21:16 INFO]: Enabled plugin EpicGuard version 7.1.0 by neox`

**Comment by xxneox** [comment]
Fixed in the [latest build](https://github.com/xxneox/EpicGuard/suites/3899769731/artifacts/97275072)
